### ISSUE TITLE
Objects are not valid as a React child

### ISSUE THREAD

**Issue by willo-icon** [lifeiscontent/storybook-addon-apollo-client#127]
Just updated to 8.0.0 and I'm getting this:
```
Error: Objects are not valid as a React child (found: object with keys {$$typeof, type, key, ref, props}). If you meant to render a collection of children, use an array instead.
    at throwOnInvalidObjectType (http://localhost:6006/node_modules/.cache/storybook/1c3385a5d25e538d10b518b310c74d3ca2690b6aaffeadccd74da79736171f86/sb-vite/deps/chunk-MYEXOB6E.js?v=3e4323a5:9981:17)
    at reconcileChildFibers2 (http://localhost:6006/node_modules/.cache/storybook/1c3385a5d25e538d10b518b310c74d3ca2690b6aaffeadccd74da79736171f86/sb-vite/deps/chunk-MYEXOB6E.js?v=3e4323a5:10611:15)
    at reconcileChildren (http://localhost:6006/node_modules/.cache/storybook/1c3385a5d25e538d10b518b310c74d3ca2690b6aaffeadccd74da79736171f86/sb-vite/deps/chunk-MYEXOB6E.js?v=3e4323a5:14338:37)
    at mountIndeterminateComponent (http://localhost:6006/node_modules/.cache/storybook/1c3385a5d25e538d10b518b310c74d3ca2690b6aaffeadccd74da79736171f86/sb-vite/deps/chunk-MYEXOB6E.js?v=3e4323a5:15034:13)
    at beginWork (http://localhost:6006/node_modules/.cache/storybook/1c3385a5d25e538d10b518b310c74d3ca2690b6aaffeadccd74da79736171f86/sb-vite/deps/chunk-MYEXOB6E.js?v=3e4323a5:15962:22)
    at beginWork$1 (http://localhost:6006/node_modules/.cache/storybook/1c3385a5d25e538d10b518b310c74d3ca2690b6aaffeadccd74da79736171f86/sb-vite/deps/chunk-MYEXOB6E.js?v=3e4323a5:19806:22)
    at performUnitOfWork (http://localhost:6006/node_modules/.cache/storybook/1c3385a5d25e538d10b518b310c74d3ca2690b6aaffeadccd74da79736171f86/sb-vite/deps/chunk-MYEXOB6E.js?v=3e4323a5:19251:20)
    at workLoopSync (http://localhost:6006/node_modules/.cache/storybook/1c3385a5d25e538d10b518b310c74d3ca2690b6aaffeadccd74da79736171f86/sb-vite/deps/chunk-MYEXOB6E.js?v=3e4323a5:19190:13)
    at renderRootSync (http://localhost:6006/node_modules/.cache/storybook/1c3385a5d25e538d10b518b310c74d3ca2690b6aaffeadccd74da79736171f86/sb-vite/deps/chunk-MYEXOB6E.js?v=3e4323a5:19169:15)
    at recoverFromConcurrentError (http://localhost:6006/node_modules/.cache/storybook/1c3385a5d25e538d10b518b310c74d3ca2690b6aaffeadccd74da79736171f86/sb-vite/deps/chunk-MYEXOB6E.js?v=3e4323a5:18786:28)
```

It goes away if I disable the `storybook-addon-apollo-client` addon in `main.ts`, or if I revert to `7.3.0`.

Here are my relevant dependencies and versions:
```
"@storybook/addon-actions": "^8.5.1",
"@storybook/addon-console": "^3.0.0",
"@storybook/addon-essentials": "^8.5.1",
"@storybook/addon-interactions": "^8.5.1",
"@storybook/addon-links": "^8.5.1",
"@storybook/addon-onboarding": "^8.5.1",
"@storybook/blocks": "^8.5.1",
"@storybook/react": "^8.5.1",
"@storybook/react-vite": "^8.5.1",
"@storybook/test": "^8.5.1",
"@vitejs/plugin-react-swc": "^3.7.2",
"react": "^18.3.1",
"react-dom": "^18.3.1",
"storybook": "^8.5.1",
"storybook-addon-apollo-client": "^8.0.0",
"typescript": "^5.7.3",
"vite": "^6.0.11",
```

**Comment by lifeiscontent** [comment]
@willo-icon can you put a small reproduction together? Its working in the test project of this repo and hard to debug without one 😅

**Comment by willo-icon** [comment]
No sweat, I will try to get one going in a bit. Thanks for the quick response.

**Comment by lifeiscontent** [comment]
@philostler can you put a reproduction together?

**Comment by jnsandrew** [comment]
For me this is a combination of Storybook 8.5 AND addon-apollo-client 8.0.0. 

Downgrading storybook to 8.4.x OR addon-apollo-client to 7.3 fixes the issue.

However I also noticed that if you upgrade `@apollo/client` to the latest `3.12.x`, then everything works (so Storybook 8.5, addon-apollo-client 8.0)

**Comment by joostslijkoort** [comment]
I am running into the same problem, it could have something to do with the fact that i'm moving to react-vite. I will put a reproduction together!

**Comment by joostslijkoort** [comment]
I scaffolded[ this repo](https://github.com/joostslijkoort/react-vite-storybook-apollo-reproduction) to reproduce the issue:

**Comment by lifeiscontent** [comment]
@joostslijkoort thanks! Fixed in 8.1.0 if you run into any issues, try clearing your `node_modules/.cache` folder

**Comment by anthonyjgrove** [comment]
I am still seeing this issue in `8.1.0`.

**Comment by RickCardoso** [comment]
@anthonyjgrove , downgrading the addon to 7.3.0 works with Storybook 8.5.3.

**Comment by philostler** [comment]
Tested this with `8.1.1` this morning and still seeing the same issue. Running Storybook `8.4.7`

**Comment by lifeiscontent** [comment]
@anthonyjgrove @RickCardoso @philostler sorry for the false positive here, I've reached out to the storybook team about it and Shilman the lead maintainer is helping me find someone within storybook to help uncover what might be going on, storybook recently made react an internal dependency (they have their own version of react for addons and the story manager) and I suspect this is what might be causing the issue. Will report back once we uncover what's going on.

**Comment by lifeiscontent** [comment]
just for context: you can track more info on this here: https://github.com/storybookjs/storybook/discussions/30552

**Comment by lifeiscontent** [comment]
should be fixed in latest release now :)
